version: '3.9'

services:
    api:
        image: api
        container_name: api
        restart: always
        ports:
            - "8000:8000"
        environment:
            mongo_uri: "mongodb://host.docker.internal:27017/"
        build:
            context: './'
            dockerfile: 'Dockerfile'
            # args:
            #     SOURCE_FOLDER: 'service_example'
        command: uvicorn src.app.api:app --host 0.0.0.0 --port 8000